#!/bin/bash

if [ -z "$ENV" ]; then
  echo "💁‍♀️ Usage: ENV=staging npm run deploy"
  echo "(or production, note: not prod)"
  echo
  rm -rf ./dist
  exit 1
fi

if [ $ENV == "staging" ]
then
  FOLDER=docs-staging
  BRANCH=develop
elif [ $ENV == "production" ]
then
  FOLDER=docs
  BRANCH=main
else
  echo "🤷‍♀️ Target unknown"
  exit 1
fi

# We "deploy" to a subdirectory of the website repo now -Tom
(
  cd ~/apostrophecms/apostrophecms-website &&
  { test -z "$(git status --porcelain)" || { echo "Error: Git working directory is not clean in apostrophecms-website"; false; }; } &&
  git pull &&
  git checkout $BRANCH
) &&
rsync -a --delete ./docs/.vitepress/dist/ ~/apostrophecms/apostrophecms-website/public/docs &&
(
  cd ~/apostrophecms/apostrophecms-website &&
  git add -A . &&
  git commit -m 'docs deployment' &&
  git push
) &&
echo "Pushed to $BRANCH of apostrophecms/apostrophecms-website, a deployment should ensue."

#rsync -av --delete --exclude '.git' --exclude '**/node_modules' ./docs/.vitepress/dist static@static.apostrophecms.com:/opt/static/$FOLDER &&
#echo "Synced up to $ENV"
