#!/bin/bash

if [ -z "$ENV" ]; then
  echo "💁‍♀️ Usage: ENV=staging npm run deploy"
  echo "(or prod, NOT production, must match act)"
  echo
  rm -rf ./dist
  exit 1
fi

if [ $ENV == "staging" ]
then
  FOLDER=docs-staging
  BRANCH=develop
elif [ $ENV == "prod" ]
then
  FOLDER=docs
  BRANCH=main
else
  echo "🤷‍♀️ Target unknown"
  exit 1
fi

npm run build &&

(tar -C ./docs/.vitepress/dist -zcf - . | ssh static@static.apostrophecms.com "cat > /opt/static/static/$ENV-docs.tar.gz") &&

echo "Now run: CLOUD=website-$ENV act redeploy"
